use the correct bouncycastle version

diff --git a/scripts/slcs-init b/scripts/slcs-init
--- a/scripts/slcs-init
+++ b/scripts/slcs-init
@@ -2,7 +2,7 @@
 #
 # Execute the SLCS client
 #
-# $Id: slcs-init,v 1.3 2006/11/01 11:47:34 vtschopp Exp $
+# $Id: slcs-init,v 1.4 2006/11/03 14:19:36 vtschopp Exp $
 # Copyright (c) 2004. Members of the EGEE Collaboration. 
 # http://www.eu-egee.org
 #
@@ -27,7 +27,15 @@ for slcs_jar in $SLCS_HOME/share/java/glite-slcs-*.jar ; do
     SLCS_CP=$SLCS_CP:$slcs_jar
 done
 # external slcs libs classpath
-BOUNCY_CP=$SLCS_HOME/externals/share/java/bcprov-jdk14-134.jar
+# bouncycastle is JDK dependent
+if [ -f "$SLCS_HOME/externals/share/java/bcprov-jdk14-134.jar" ]; then
+    BOUNCY_CP=$SLCS_HOME/externals/share/java/bcprov-jdk14-134.jar
+elif [ -f "$SLCS_HOME/externals/share/java/bcprov-jdk15-134.jar" ]; then
+    BOUNCY_CP=$SLCS_HOME/externals/share/java/bcprov-jdk15-134.jar
+else
+    echo "ERROR: BouncyCastle: bcprov-jdk14-134.jar or bcprov-jdk15-134.jar not found"
+    exit 1
+fi
 COMMONS_CP=$SLCS_HOME/externals/share/java/commons-cli-1.0.jar:$SLCS_HOME/externals/share/java/commons-codec-1.3.jar:$SLCS_HOME/externals/share/java/commons-collections-3.2.jar:$SLCS_HOME/externals/share/java/commons-configuration-1.2.jar:$SLCS_HOME/externals/share/java/commons-httpclient-3.0.1.jar:$SLCS_HOME/externals/share/java/commons-lang-2.1.jar:$SLCS_HOME/externals/share/java/commons-logging.jar
 JHTML_CP=$SLCS_HOME/externals/share/java/jericho-html-2.3.jar
 LOG4J_CP=$SLCS_HOME/externals/share/java/log4j.jar:$SLCS_HOME/externals/share/java/log4j-1.2.8.jar
